//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUIDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_history
    {
        public long email_history_id { get; set; }
        public string email_type { get; set; }
        public string send_to { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public string notification_type { get; set; }
        public Nullable<long> send_by { get; set; }
        public System.DateTime send_time { get; set; }
    }
}
