//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUIDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday
    {
        public int holiday_id { get; set; }
        public string country_code { get; set; }
        public string holiday_year { get; set; }
        public System.DateTime holiday_date { get; set; }
        public string holiday_name { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> floating { get; set; }
    }
}
