//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUIDataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PLS20Entities : DbContext
    {
        public PLS20Entities()
            : base("name=PLS20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<promo_code_ae> promo_code_ae { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<email_history> email_history { get; set; }
        public virtual DbSet<email_history_load> email_history_load { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<loadPLS20> loadPLS20 { get; set; }
        public virtual DbSet<international_holidays> international_holidays { get; set; }
    }
}
