//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedUIDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.promo_code_ae = new HashSet<promo_code_ae>();
            this.loads = new HashSet<loadPLS20>();
            this.loads1 = new HashSet<loadPLS20>();
            this.loads2 = new HashSet<loadPLS20>();
            this.users1 = new HashSet<user>();
            this.users11 = new HashSet<user>();
        }
    
        public long person_id { get; set; }
        public string password { get; set; }
        public string accept_email { get; set; }
        public string email_address { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string userid { get; set; }
        public string status { get; set; }
        public System.DateTime date_created { get; set; }
        public long created_by { get; set; }
        public System.DateTime date_modified { get; set; }
        public long modified_by { get; set; }
        public string middle_name { get; set; }
        public string title { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public Nullable<long> org_id { get; set; }
        public Nullable<long> location_id { get; set; }
        public string im_flag { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<long> brand_id { get; set; }
        public string multiip_allowed { get; set; }
        public string acceptance_ind { get; set; }
        public string user_reg_token { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<long> parent_person_id { get; set; }
        public string master { get; set; }
        public string use_profile_contact { get; set; }
        public string cust_serv_info_type { get; set; }
        public string auth_token { get; set; }
        public string internal_external { get; set; }
        public Nullable<System.DateTime> password_expiry { get; set; }
        public Nullable<System.DateTime> password_modified { get; set; }
        public string watched_push_enabled { get; set; }
        public string critical_push_enabled { get; set; }
        public Nullable<long> person_id_fin_data { get; set; }
        public string position_fin_data { get; set; }
        public string department_fin_data { get; set; }
        public bool upcharge_nag_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promo_code_ae> promo_code_ae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loadPLS20> loads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loadPLS20> loads1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loadPLS20> loads2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users1 { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users11 { get; set; }
        public virtual user user2 { get; set; }
    }
}
